---
title: "ippi_mapping"
author: "Andrew Wells"
date: "1/17/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(sf)
library(tidyverse)
library(tmap)
library(tmaptools)
library(raster)
#raster is for mac

options(scipen = 999)
```

```{r}
#Loading data
df <- read_csv("~/Desktop/Jobs/Malawi/Project Implementation/Initiatives:project components/IPPI/ippi_report/data/ippi.csv")

#Delete any rows that do not have coordinates
df %>%
  drop_na(coordinates)
```

```{r}
# Save the shapefile as a dataframe

malawi <- sf::read_sf("~/Desktop/Jobs/Malawi/Malawi Mapping/MWI_adm1.shp")
```

```{r}
ggplot() + geom_sf(data = malawi) + coord_sf(crs = st_crs(4326)) + theme_minimal()
```
```{r}
coords <- df %>%
  drop_na(coordinates) %>%
  select(title, lat, long, amount_usd_eur, type)


point_geo <- st_as_sf(coords,
                      coords = c(x = "long", y = "lat"),
                      crs = 4326) 
```

```{r}
st_join(point_geo, malawi, join = st_within)
```
```{r}
tm_shape(malawi) +
  tm_fill() +
  tm_shape (point_geo) +
  tm_bubbles(col = "type", size = "amount_usd_eur") # Set the color and size of the geo-located points
```
```{r}
tmap_mode("view")

tmap_last()
```







